DIRECTORY_MODERATION = 'config/moderation/'
DIRECTORY_POLLS = 'config/poll/'
DIRECTORY_SEARCH = 'config/search/'
DIRECTORY_STICKY_MESSAGES = 'config/sticky_message/'
DIRECTORY_TEST_COLLECTOR = 'config/test_collector/'
DIRECTORY_TEST_REPLAY = 'config/test_replay/'